
abstract: substitute values into files before install
author: Ruslan U. Zakirov <Ruslan.Zakirov@gmail.com>
build_requires: 
  Test::File::Contents: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Module-Install-Substitute
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cwd: 0
  File::Spec: 0
  File::Temp: 0
version: 0.02
